### PR TITLE
fix-issue-12 - Add list of unsupported devices

### PR DESCRIPTION
**Pull request by ekomlenovic**

### CODE REVIEW

**Comment by Selviniahh** [comment]
I getting **Device id=0xc08b, name=G502 Hero - is not supported yet!**

**Comment by ekomlenovic** [comment]
Yes, that's what it's supposed to return.  
I haven't added support for the g502, just a clearer error message for all devices not yet supported.

**Comment by Selviniahh** [comment]
Can you somehow add support for g502 hero

**Comment by NerdicaLabs** [comment]
Add support for G502 Hero?

**Pull request merged**
